
development:
  adapter: mysql2
  database: provisiondemo
  username: prov
  password: prov

test:
  adapter: mysql2
  database: provisiondemo
  username: prov
  password: prov

production:
  adapter: mysql2
  database: provisiondemo
  username: prov
  password: prov
